import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by create next app",
  link:"/next.js"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <link rel="icon" href="/next.svg" />
      </head>
      <body className={inter.className}>
        {children}
        <footer>Ebru Özdemir © 2024 - All Rights Reserved.</footer>
      </body>
    </html>
  );
}
